trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 4
  train_dataset: /mnt/d/siga_21/withAlpha/training
  valid_dataset: /mnt/d/siga_21/withAlpha/training
  valid_split: temp/sndd_det3d/sndd_total_split_val.txt
  train_split: temp/sndd_det3d/sndd_total_split_train.txt
#  train_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training
#  valid_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training
  batch_size: 4
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
det_3d:
  preprocessed_path: temp/sndd_det3d/
  compute_anchor: false
  score_threshold: 0.5
  test_score_threshold: 0.75
  rotate_pitch_when_project: true
model:
  img_shape_x: 800
  img_shape_y: 800
hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled