trainer:
  learning_rate: 1e-4
  gpu: 1
  num_worker: 0
  train_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\training
  valid_dataset: D:\DATASET\KITTI\3DDetection\data_object_image_2\testing
#  train_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training
#  valid_dataset: C:\Users\yilin\Documents\Tencent Files\1787609016\FileRecv\training\training
  batch_size: 4
  auto_lr_find: false
  resume_from_checkpoint:
  evaluate: false
det_3d:
  visualDet3D_config_path: C:\repo\python\src\3d_detection\Yolo3D_test.py
  preprocessed_path: temp/det3d/anchors/
  compute_anchor: true
  score_threshold: 0.5
  rotate_pitch_when_project: false
model:
  img_shape_x: 1280
  img_shape_y: 288
hydra:
  run:
    dir: .
  output_subdir: null
#  job_logging: disabled
#  hydra_logging: disabled